on:
  push:
    branches:
      - develop
      - main
  pull_request: # Trigger the workflow on pull requests targeting the specified branches
      branches:
        - develop
        - main


jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
            cd backend
            npm install
            npm test